### ISSUE TITLE
Windows 10 Support

### ISSUE THREAD

**Issue by puchmu** [MSOpenTech/cordova-plugin-websql#44] opened 2015-12-21 14:57 UTC
Is it planned that this plugin will work on Windows 10 Universal Apps that are built with cordova and Visual Studio 2015?
Right now when I add the plugin and then run my project I get the following error:

Severity Code Description Project File Line Suppression State Error
Your project.json doesn't list 'win10' as a targeted runtime. You should add '"win10": { }' inside your "runtimes" section in your project.json, and then re-run NuGet restore. 

Also, it states that the error occurs in Microsoft.NuGet.targets at line 211.

**Comment by shamsealam** [comment] 2016-01-07 05:44
I am also getting the same issue.

Can someone look into this?

**Comment by rakatyal** [comment] 2016-01-10 10:38
Could you try specifying the architecture along with the build instead of the default 'Any CPU' option?

**Comment by puchmu** [comment] 2016-01-11 09:24
I got it to work just now with the following steps:
In Cordova CLI, just use cordova run windows --arch="x64" OR cordova run windows --arch="x86", both work fine.

 To get it to work with VS 2015, you have to copy the "Debug" folder from <Cordova-Project>/plugins/cordova-plugin-websql/src/windows/SQLite.Proxy/bin/x64/Debug one Directory up to <Cordova-Project>/plugins/cordova-plugin-websql/src/windows/SQLite.Proxy/bin/Debug. You can also use the x86-Debug folder, however you must use the same target then in VS2015 to deploy to. So in VS 2015 you have to select either x86 OR x64 as the solution target.

It would be nice if you could get the AnyCPU-Solution to run, because if you want to debug it using VS2015 it is not a good solution to copy the Debug folder.

**Comment by rakatyal** [comment] 2016-01-11 19:09
This plugin is based on a .Net implementation that for Windows 10 supports only architecture specific builds. We are working on better error messages and the issue is being tracked at https://issues.apache.org/jira/browse/CB-10234.

**Comment by jantonsg** [comment] 2016-01-15 11:23
Hi, 
I have been using this plugin with Windows 8.1 (desktop and phone) without problems. Now we are planning to upgrade to Windows10 (desktop and phone). 
Until now you have explained us how to deploy for desktop but I have some questions to make it work on mobile. 
If I need to make it work on Windows10 mobile (windowsPhone). Can I use ARM arch? Do you know If I Have to make any change?
Thanks so much,

**Comment by rakatyal** [comment] 2016-01-15 19:36
Yes you can use ARM for Windows 10 phones.

**Comment by e3duardo** [comment] 2016-01-24 17:46
I have to have sdk 8 or 8.1 to build on arm or x86? I'm still getting same error on these plataforms.

**Comment by Hasanajouz** [comment] 2016-01-26 14:20
Still getting openDatabse is undefined error using windows 10 x64 or x86
i moved the debug one level up.
using the last plugin
nothing helped.
Thanks.

**Comment by rakatyal** [comment] 2016-01-26 19:42
@e3duardo: I believe so. Which sdk are you using?
@Hasanajouz: Do you get the same error on building for other windows platforms as well?

**Comment by e3duardo** [comment] 2016-01-26 20:52
it's worked after instalation of the skd 8 and 8.1. But vs2015 can't recognize my phone anymore in Windows-ARM. I have to build on vs, and install manually on phone the appx.

**Comment by e3duardo** [comment] 2016-01-26 22:40
ps, I'm using windows 10 on notebook and phone

**Comment by Hasanajouz** [comment] 2016-01-27 07:45
@rakatyal I can't test it on ARM right now because testing on my windows 10 mobile is not working with me anymore using the last build even on the emulators.
I didn't try it on windows 8.1 because there are other things that will not work.
and of course on android there is no problem.

and I tried other websql plugins non worked. and they give the same error.

**Comment by Hasanajouz** [comment] 2016-01-28 08:13
@rakatyal 
it is working good when i call the "openDatabse" function on click of a button.
But on page load or page initialize it will not.
So what is the best page event to call it on?

**Comment by puchmu** [comment] 2016-01-28 12:21
As this is a cordova plugin you can call openDatabase after the deviceready event was fired, so e.g.:

`document.addEventListener("deviceready", function(){
    window.openDatabase(...);
}, false);`

On page load is too early as the cordova plugins have to be initialised first to use them safely

**Comment by Hasanajouz** [comment] 2016-01-28 12:33
@puchmu thanks very much.
I forgot this event.
I tried all but this.
now it is working.

**Comment by rakatyal** [comment] 2016-01-28 18:41
Great. Closing this issue now, since it has diverged a lot from the original post. Please create a new one if you face more problems.

**Closed as completed by rakatyal** 2016-01-28 18:41 UTC
